/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nzuki
 */
public class Products extends javax.swing.JFrame {
    Statement st;
ResultSet rs;
Connection conn;
dbconnect con;
PreparedStatement pst;

            String driver="org.postgresql.Driver";
            String url="jdbc:postgresql://localhost:5432/postgres";
            String username="postgres";
            String password="awesome";

    /**
     * Creates new form Products
     */
    public Products() throws Exception {
        initComponents();
        con=new dbconnect();
       st= con.getConnection().createStatement();
     
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
        
        
  
 
        try{
               
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
               
                

                String sql="select * from products ORDER BY quantity ASC" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();
                
                
               
         
       
              
                
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        qnty = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        Edit = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel11.setForeground(new java.awt.Color(0, 51, 51));
        jPanel11.setToolTipText("");
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -20, -1, -1));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("OmegaPOS");
        jPanel11.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("PRODUCTS");
        jPanel11.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 380, 90));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 90));

        jLabel13.setBackground(new java.awt.Color(0, 51, 51));
        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Product Name");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, -1));

        pname.setToolTipText("");
        pname.setBorder(null);
        pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnameKeyTyped(evt);
            }
        });
        jPanel10.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 20));
        jPanel10.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, 10));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Quantity");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, -1));

        qnty.setToolTipText("");
        qnty.setBorder(null);
        qnty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qntyKeyTyped(evt);
            }
        });
        jPanel10.add(qnty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 20));
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 240, 10));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit.setBackground(new java.awt.Color(255, 255, 255));
        Edit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(0, 51, 51));
        Edit.setText("Update");
        Edit.setInheritsPopupMenu(true);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel13.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, 30));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 51, 51));
        jButton15.setText("Delete");
        jButton15.setInheritsPopupMenu(true);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 90, 30));

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 51, 51));
        jButton16.setText("Clear");
        jButton16.setInheritsPopupMenu(true);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 51, 51));
        jButton17.setText("Save");
        jButton17.setInheritsPopupMenu(true);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 200));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Product Id");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 170, -1));

        pid.setToolTipText("");
        pid.setBorder(null);
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pidKeyTyped(evt);
            }
        });
        jPanel10.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 20));
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 240, 10));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnameKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_pnameKeyTyped

    private void qntyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntyKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_qntyKeyTyped

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            conn=DriverManager.getConnection(url, username, password);

            String sql="update products set product_name=?,quantity=? where product_id=?";

            pst=conn.prepareStatement(sql);

            pst.setString(1, pname.getText());
            pst.setString(2, qnty.getText());
            pst.setString(3, pid.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Updated");
            int average = 0;
            int sum = 0;

            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

            try{

                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);

                String sq="select * from products ORDER BY quantity ASC" ;
                pst=conn.prepareStatement(sq);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();

                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_EditActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            conn=DriverManager.getConnection(url, username, password);

            String sql="delete from products where product_id=?";

            pst=conn.prepareStatement(sql);

            pst.setString(1, pid.getText());
            int input=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected record?", "DELETE",JOptionPane.YES_NO_OPTION);
            if(input==JOptionPane.YES_OPTION){

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Deleted!");
                int average = 0;
                int sum = 0;

                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

                try{

                    Class.forName(driver);
                    conn=DriverManager.getConnection(url, username, password);

                    String sq="select * from products ORDER BY quantity ASC" ;
                    pst=conn.prepareStatement(sq);
                    rs=pst.executeQuery();

                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    model=(DefaultTableModel)jTable1.getModel();

                   
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);

                }

            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        pname.setText("");
        qnty.setText("");
        pid.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName(driver);
            conn=DriverManager.getConnection(url, username, password);
            String sq="insert into products (product_id, product_name, quantity) values (?,?,?)";
            pst=conn.prepareStatement(sq);

            pst.setString(1, pid.getText());
            pst.setString(2, pname.getText());
            pst.setString(3, qnty.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved");
            //jTable1.setDefaultEditor(Object.class, null);
            int average = 0;
            int sum = 0;

            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

            try{

                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);

                String sql="select * from products ORDER BY quantity ASC" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();

                

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        String produc = (String)model.getValueAt(selectedRowIndex, 0);
        String id = (String)model.getValueAt(selectedRowIndex, 2);
        String qty = (String)model.getValueAt(selectedRowIndex, 1);
        pid.setText(id);
        qnty.setText(qty);
        pname.setText(produc);

    }//GEN-LAST:event_jTable1MouseClicked

    private void pidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pidKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Products().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField qnty;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField sname1;
    private javax.swing.JTextField sname2;
    // End of variables declaration//GEN-END:variables
}
